language: php

php:
  - 7.2
  - 7.4

env:
    global:
        - DEFAULT=1 CI=1

matrix:
    include:
        - php: 7.2
          env: PREFER_LOWEST=1

        - php: 7.4
          env: CHECKS=1 DEFAULT=0
          
    fast_finish: true

before_script:
    - phpenv config-add ci/travis.php.ini
    - if [[ $PREFER_LOWEST != 1 ]]; then composer install --no-interaction; fi;
    - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-lowest --no-interaction --prefer-dist --prefer-stable ; fi;

script:
    - if [[ $DEFAULT == 1 ]]; then vendor/bin/codecept run --coverage-xml ; fi
    - if [[ $CHECKS == 1 ]]; then composer cs-check ; fi

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
