language: php

sudo: false

php:
    - 7.1
    - 7.3

env:
    global:
        - DEFAULT=1 CI=1

matrix:
    include:
        - php: 7.1
          env: PREFER_LOWEST=1

        - php: 7.2
          env: CHECKS=1 DEFAULT=0

          fast_finish: true

before_script:
    - if [[ $PREFER_LOWEST != 1 ]]; then composer update --no-interaction; fi;
    - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-lowest --no-interaction --prefer-dist --prefer-stable ; fi;

script:
    - if [[ $DEFAULT == 1 ]]; then vendor/bin/codecept run --coverage-xml ; fi
    - if [[ $CHECKS == 1 ]]; then composer phpstan ; fi
    - if [[ $CHECKS == 1 ]]; then composer cs-check ; fi

    - vendor/bin/phpcs src --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml
    - vendor/bin/codecept run --env isolated --coverage-xml

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
